version: '3.8'

services:
  db:
    image: postgres:15
    container_name: weather-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - weather-network

  api:
    build: .
    container_name: weather-api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      API_KEY: ${API_KEY}
      DB_NAME: ${DB_NAME}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      HOST: db
      PORT: 5432
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - weather-network

volumes:
  pgdata:

networks:
  weather-network:
